// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkKCz44fps84zeJoFVp9eBgu2ez9ZifSI',
    appId: '1:473168434465:web:8068e76a11c971d203da60',
    messagingSenderId: '473168434465',
    projectId: 'projetpfe-d4ede',
    authDomain: 'projetpfe-d4ede.firebaseapp.com',
    storageBucket: 'projetpfe-d4ede.firebasestorage.app',
    measurementId: 'G-6NXD9H37E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdCVsBcwrPDExUEnCVvUcqqF3uweXAuvA',
    appId: '1:473168434465:android:b47930986dd5c3a203da60',
    messagingSenderId: '473168434465',
    projectId: 'projetpfe-d4ede',
    storageBucket: 'projetpfe-d4ede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDJBdGmcbZqo0rACa6uNYvy8LIj4uIW4',
    appId: '1:473168434465:ios:f143ff2570ad5a4303da60',
    messagingSenderId: '473168434465',
    projectId: 'projetpfe-d4ede',
    storageBucket: 'projetpfe-d4ede.firebasestorage.app',
    iosClientId: '473168434465-nib23pmar7dmct5gfb6jdgnulk2pm108.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrDJBdGmcbZqo0rACa6uNYvy8LIj4uIW4',
    appId: '1:473168434465:ios:f143ff2570ad5a4303da60',
    messagingSenderId: '473168434465',
    projectId: 'projetpfe-d4ede',
    storageBucket: 'projetpfe-d4ede.firebasestorage.app',
    iosClientId: '473168434465-nib23pmar7dmct5gfb6jdgnulk2pm108.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkKCz44fps84zeJoFVp9eBgu2ez9ZifSI',
    appId: '1:473168434465:web:94e1ef201050548203da60',
    messagingSenderId: '473168434465',
    projectId: 'projetpfe-d4ede',
    authDomain: 'projetpfe-d4ede.firebaseapp.com',
    storageBucket: 'projetpfe-d4ede.firebasestorage.app',
    measurementId: 'G-5LM8GNXY10',
  );
}
